[package]
name = "kdl-schema"
description = ""
license-file = "LICENSE"
version = "0.1.1-alpha.0"
authors = ["Dustin Yost <dustin.yost.t@gmail.com>"]
repository = ""
keywords = []
categories = []
edition = "2018"

[dependencies]
kdl = "3.0"
log = { version = "0.4", features = ["std"] }
